name: Build and test

on:
  issue_comment:
    types: [created, edited]
permissions:
  pull-requests: write
  issues: write
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
  ubuntu:
    name: Build and test AMD64 Ubuntu ${{ matrix.ubuntu }}
    runs-on: ubuntu-latest
    if: "(github.event_name == 'push' ||  (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/rerun-unit')))"
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [18.04]
    env:
      UBUNTU: ${{ matrix.ubuntu }}
    steps:
      - name: GitHub Script
        uses: actions/github-script@v5.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          script: |
            const creator = context.payload.sender.login

            const commentBody = "comment user id is {{ context.comment.user.id }} \n
             job id is {{ github.job}} " 
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody 
            })