name: Build and test


on: 
  push:
    branches: [main]
  issue_comment:
    types: [created, edited]
permissions:
  pull-requests: write
  issues: write
jobs:
  ubuntu:
    name: Build and test AMD64 Ubuntu ${{ matrix.ubuntu }}
    runs-on: ubuntu-latest
    if: "(github.event_name == 'push' ||  (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/rerun-unit')))"
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [18.04]
    env:
      UBUNTU: ${{ matrix.ubuntu }}
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - name: Get Job URL
        if: "github.event_name == 'issue_comment'"
        id: get_job_url
        run:  |        
          echo "::set-output name=job-url::'test'"
      - name: Test get job url 
        if: "github.event_name == 'issue_comment'"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          JOB_URL: ${{ steps.get_job_url.job-url }}
          TEST_ENV: "ttt"
        run: |
          echo "${JOB_URL}"
          echo "${TEST_ENV}"
      - name: Create reply comment on PR
        uses: actions/github-script@v5.0.0 
        if: "github.event_name == 'issue_comment'"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          JOB_URL: ${{ steps.get_job_url.job-url }}
        with:
          script: |
            const { JOB_URL } = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `$JOB_URL`
            })

        
