name: Build and test

on:
  issue_comment:
    types: [created, edited]
permissions:
  pull-requests: write
  issues: write
jobs:
  ubuntu:
    name: Build and test AMD64 Ubuntu ${{ matrix.ubuntu }}
    runs-on: ubuntu-latest
    if: "(github.event_name == 'push' ||  (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/rerun-unit')))"
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [18.04]
    env:
      UBUNTU: ${{ matrix.ubuntu }}
    outputs:

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - name: Echo Environment Variables for test
        run: echo "user name is ${{ env.GITHUB_ACTOR }}, run id is ${{ env.GITHUB_RUN_ID }}"
