name: Build and test


on: 
  push:
    branches: [main]
  issue_comment:
    types: [created, edited]
permissions:
  pull-requests: write
  issues: write
jobs:
  ubuntu:
    name: Build and test AMD64 Ubuntu ${{ matrix.ubuntu }}
    runs-on: ubuntu-latest
    if: "(github.event_name == 'push' ||  (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/rerun-unit')))"
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [18.04]
    env:
      UBUNTU: ${{ matrix.ubuntu }}
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - name: Echo Environment Variables for test
        run:  |        
          echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      - name: Create reply comment on PR
        uses: actions/github-script@v5.0.0
        with:
          script: |
            const commentBody = "runner url is  $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID " 
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody 
            })

        
