name: Run Checks
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [ created ]
jobs:
   rerun-checks:
      runs-on: ubuntu-latest
      steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/run-checks'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
      - uses: actions/checkout@v1
        if: steps.check.outputs.triggered == 'true'
      - uses: LouisBrunner/checks-action@v1.2.0
        if: steps.check.outputs.triggered == 'true'
        id: init
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test With Init (pull_request )
          status: in_progress
      - run: sleep 30
      - uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.init.outputs.check_id }}
          conclusion: success

  