on:
  pull_request_review:
  pull_request_review_comment:
    # types: [ created ]

jobs:
    add-labels-issue:
      runs-on: ubuntu-latest
      if: contains(github.event.comment.body, '/add-invalid') && github.event_name == 'pull_request_review_comment'
      steps:
      - uses: actions/checkout@v2
      - name: Add label
        uses: actions/github-script@0.9.0
        if: success()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['invalid']
            })
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Added invalid :)!'
            })