on:
  pull_request_review_comment:
  pull_request_review:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/run-checks'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v1
      - uses: LouisBrunner/checks-action@v1.1.1
        id: init
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test With Init
          status: in_progress